---
- name: Remove Grafana
  hosts: hosts
  become: yes

  tasks:
    - name: remove apt key
      ansible.builtin.apt_key:
        url: https://packages.grafana.com/gpg.key 
        id: 0E22EB88E39E12277A7760AE9E439B102CF3C0C6
        state: absent
    - name: remove grafana to sources.list
      ansible.builtin.apt_repository:
        repo: deb https://packages.grafana.com/oss/deb stable main
        filename: grafana
        state: absent
    - name: remove Grafana
      ansible.builtin.apt:
        name: grafana
        state: absent
